### ISSUE TITLE
wtfudge

### ISSUE THREAD

**Issue by matthewalexanderwhite** [matthewalexanderwhite/MyFirstApp2-2#1]
testing...incoming communication...I have uploaded my current tutorial project from Android Studio to GitHub (MyFirstApp2-2). Ignore 'MyFirstApp2", as this is empty. My previous issue has been resolved. I am now at snag#2. Everything looks good when running the app, but when I attempt to enter a message in the empty text box on the home screen (when i tap the 'Enter a message' to enter a message) the app automatically switches from the home screen to a secondary screen which is intended to display the entered text AFTER pressing send and thus I am unable to enter said text and thereby display it on secondary screen. The tutorial I am following can be found here:https://developer.android.com/training/basics/firstapp

**Comment by matthewalexanderwhite** [comment]
testing...incoming communication...I have uploaded my current tutorial project from Android Studio to GitHub (MyFirstApp2-2). Ignore 'MyFirstApp2", as this is empty. My previous issue has been resolved. I am now at snag#2. Everything looks good when running the app, but when I attempt to enter a message in the empty text box on the home screen (when i tap the 'Enter a message' to enter a message) the app automatically switches from the home screen to a secondary screen which is intended to display the entered text AFTER pressing send and thus I am unable to enter said text and thereby display it on secondary screen. The tutorial I am following can be found here:https://developer.android.com/training/basics/firstapp

**Comment by andersonreinkordt** [comment]
@matthewalexanderwhite I noticed the `onClick` attribute is set to call `sendMessage` in the `EditText` element of your `activity_main.xml`. It seems like that should be in the `Button` element?

```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context=".MainActivity">
    <EditText
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:inputType="textPersonName"
            android:ems="10"
            android:id="@+id/editText" android:layout_marginTop="16dp"
            app:layout_constraintTop_toTopOf="parent" android:layout_marginStart="16dp"
            app:layout_constraintStart_toStartOf="parent" android:layout_marginLeft="16dp"
            android:hint="@string/edit_message" app:layout_constraintHorizontal_bias="0.5"
            app:layout_constraintEnd_toStartOf="@+id/button" android:onClick="sendMessage"/>
    <Button
            android:text="@string/button_send"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:id="@+id/button" app:layout_constraintStart_toEndOf="@+id/editText" android:layout_marginLeft="16dp"
            android:layout_marginStart="16dp" app:layout_constraintBaseline_toBaselineOf="@+id/editText"
            app:layout_constraintHorizontal_bias="0.5" app:layout_constraintEnd_toEndOf="parent"
            android:layout_marginRight="16dp" android:layout_marginEnd="16dp"/>
```
